# Generated by Django 3.2 on 2022-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0002_auto_20221006_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE')], max_length=4)),
            ],
        ),
    ]
