# Generated by Django 3.2 on 2022-10-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0004_comment_either'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
